project:
  type: book
  output-dir: docs

book:
  title: "DSA 554 3.0 Spatio-temporal Data Analysis"
  author: "Thiyanga S. Talagala"
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "01-chap1.qmd"
    - "02-chap2.qmd"
    - "03-chap3.qmd"
    - "04-chap4.qmd"
    - "05-chap5.qmd"
    - "06-chap6.qmd"
    - "07-chap07.qmd"
    - "08-chap8.qmd"
    - "09-chap9.qmd"
    - "10-chap10.qmd"
    - "11-chap11.qmd"
    - "12-chap12.qmd"
    - "13-chap13.qmd"
    - "refs.qmd"
  sidebar:
    style: "docked"

bibliography: thesisrefs.bib
csl: american-statistical-association.csl


format:
  monashthesis-html: default
  monashthesis-pdf: default
